---
- name: tester install
  hosts: linux-testers
  
  vars:
    ansible_password: changeme
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Install Net-utils
      apt:
        name: net-tools
        state: present

    - name: Install vim
      apt:
        name: vim
        state: present

    - name: Install Terminator
      apt:
        name: terminator
        state: present

    - name: Install htop
      apt:
        name: htop
        state: present

    - name: Install 
      apt: 
        name: nmap
        state: present